#!/bin/sh

export POSTGRES_USERNAME="${POSTGRESS_USERNAME:=localdb}"
export POSTGRES_PASSWORD="${POSTGRES_PASSWORD:=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c16)}"
export POSTGRES_PORT="${POSTGRES_PORT:=5432}"
export POSTGRES_CONTAINER="${POSTGRES_CONTAINER:=tasque_be_database}"
export TASQUE_DATABASE_PASSWORD="${TASQUE_DATABASE_PASSWORD:=${POSTGRES_PASSWORD}}"
export TASQUE_DATABASE_USERNAME="${TASQUE_DATABASE_USERNAME:=${POSTGRES_USERNAME}}"
export TASQUE_DATABASE_PORT="${TASQUE_DATABASE_PORT:=${POSTGRES_PORT}}"
export TASQUE_DATABASE_URL="${TASQUE_DATABASE_URL:=localhost}"

echo "Database password: ${POSTGRES_PASSWORD}"

docker stop ${POSTGRES_CONTAINER} || true
docker run --name ${POSTGRES_CONTAINER} --rm \
  -p 5432:${POSTGRES_PORT} \
  -e POSTGRES_PASSWORD=${POSTGRES_PASSWORD} -e POSTGRES_USER=${POSTGRES_USERNAME} \
  -d \
  postgres
flyway -url jdbc:postgresql://localhost:5432/postgres -user $TASQUE_DATABASE_USERNAME -password $TASQUE_DATABASE_PASSWORD